[project]
name = "openxc2064"
version = "0.1.0"
description = "An open-source toolchain and development platform for the Xilinx XC2064, the first FPGA."
readme = "README.md"
authors = [{ name = "Satya Jhaveri" }, { name = "Ben Saunders" }]
requires-python = ">=3.10"
dependencies = [
    "lark>=1.3.1",
    "matplotlib>=3.10.9",
    "openpyxl>=3.1.5",
    "tqdm>=4.70.0",
]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.7",
]

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false


