// HDL Grammar definition for custom HDL for openxc2064
// Can use https://www.lark-parser.org/ide/ to visualize and test grammar interactively

start: module+

// Module definition
module: "module" IDENT "(" port_list ")" ";" module_contents "endmodule"

// Ports for the modules
port_list: port ("," port)* // must have at least one port
port: DIRECTION ["reg"] IDENT
    | DIRECTION ["reg"] RANGE IDENT

DIRECTION: "input" | "output" | "inout"



// Module body:
module_contents: (wire_decl | reg_decl | assign_stmt | instance)*


// wire / reg declarations:
wire_decl: "wire" IDENT ";"
    | "wire" RANGE IDENT ";"

reg_decl: "reg" IDENT ";"
    | "reg" RANGE IDENT ";"


always_comb: "always" ":" "comb" statement // no choice of sensitivity list - we will infer this based on the block body
always_seq : "always" ":" "seq"  "@" "(" always_sens_seq  ")" statement

always_sens_seq: "posedge" IDENT
               | "negedge" IDENT  // only one signal for now

// Procedural assignments (for inside always blocks)
proc_assign: IDENT (INDEX | RANGE)? PROC_OP expression ";"
PROC_OP: "=" | "<=" // todo: should we just always support "=" and chose based on always block type?

// body of always blocks:
statement: proc_assign
         | if_stmt
         | "begin" statement+ "end"  -> block
    
if_stmt: "if" "(" expression ")" statement ["else" statement]



// assign statements:
assign_stmt: "assign" assign_stmt_lhs "=" expression ";"

assign_stmt_lhs: IDENT
    | IDENT INDEX
    | IDENT RANGE

?expression: expr_or

?expr_or: expr_or OR expr_and   -> bin_op
        | expr_and

?expr_and: expr_and AND expr_eq   -> bin_op
         | expr_eq

?expr_eq: expr_eq EQ expr_add   -> bin_op
         | expr_add

?expr_add: expr_add ADD expr_mul   -> bin_op
          | expr_mul

?expr_mul: expr_mul MUL expr_unary   -> bin_op
          | expr_unary

?expr_unary: UNARY expr_unary   -> unary_op
            | expr_primary

?expr_primary: atom
              | "(" expression ")"

atom: IDENT         -> ident_only
    | IDENT INDEX   -> ident_index
    | IDENT RANGE   -> ident_range
    | NUMBER        -> number_only

OR: "||"
AND: "&&"
EQ: "==" | "!="
ADD: "+" | "-"
MUL: "*" | "/"
UNARY: "-" | "!"

// instances:
instance: module_name ["#" "(" param_list ")"] module_instance_name "(" connection_list ")" ";"

module_name: IDENT
module_instance_name: IDENT

param_list: param ("," param)*
param: "." IDENT "(" expression ")" // force named parameters

connection_list: connection ("," connection)*
connection: "." IDENT "(" expression ")" // force named connections



// Utility rules
RANGE: "[" NUMBER ":" NUMBER "]" // e.g., [7:0]
INDEX: "[" NUMBER "]" // e.g., [3]
IDENT: /[a-zA-Z_][a-zA-Z0-9_]*/ // Identifiers (alphanumeric string starting with letter or underscore)
NUMBER: /[0-9]+('[bh][0-9A-Fa-f]+)?/
COMMENT: /\/\/[^\n]*/ // Single line comment
MULTILINE_COMMENT: "/*" /(.|\n)*?/ "*/"
%ignore /[ \t\r\n]+/ // Ignore whitespace
%ignore COMMENT
%ignore MULTILINE_COMMENT
